GET http://localhost:8080/api/employees
Accept: application/json

###
GET http://localhost:8080/api/employees/2
//GET http://localhost:8080/api/employees/{{employeeId}}
Accept: application/json

###


POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "firstName": "efffanew뉴",
  "lastName": "Perezaaaaaaaaaaa",
  "email": "hector@code.com"
}

###


PUT localhost:8080/api/employees
Content-Type: application/json

{
  "id" : 13,
  "firstName": "dddeefe",
  "lastName": "efef",
  "email": "sfsf@code.com"
}

###
DELETE localhost:8080/api/employees/13
//DELETE localhost:8080/api/employees/{{employeeId}}